export const error_codes = [
    { category: "Request Token", errorCode: "0001", errorMessage: "Pay Data is Required", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "So Many Parameters", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Merchant id is Required", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Merchant id is Not Found", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Invoice Number is Required", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Amount is Required", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Amount is Invalid (equal zero)", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Amount is Invalid Format", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Currency Code is Required", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Currency Code is Invalid Format", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Frontend URL is Invalid Format", description: "" },
    { category: "Request Token", errorCode: "0001", errorMessage: "Backend URL is Invalid Format", description: "" },
    { category: "Request Token", errorCode: "0004", errorMessage: "Authorization Fail. Sign Failed", description: "" },
    { category: "Request Token", errorCode: "0020", errorMessage: "Duplicate Invoice No", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Payment Token is Required", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Payment Token is Invalid", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Payment Code is Required", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Payment Code hadn’t found", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Pay Data is Required", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Pay Data is Invalid", description: "Decryption Failed." },
    { category: "Do Payment", errorCode: "0001", errorMessage: "USD is available for only Visa/Master card.", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Visa/Master card is available for USD.", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Name is Invalid Format", description: "Name can't be less than 3 characters & more than 30 characters" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Phone No is Required", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Phone No is Invalid Format", description: "Phone number must be between 9-11 digits (Pattern: ^(09)\\d{7,9}$)" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Email is Invalid Format", description: "Email format must be valid." },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Number is Required", description: "Card number required for Visa/Master." },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Number is Invalid Format", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Expiry Month is Required", description: "2 digits of card expiry month." },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Expiry Month is Invalid Format", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Expiry Year is Required", description: "2 digits of card expiry year." },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Expiry Year is Invalid Format", description: "" },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Security Code is Required", description: "3 digits of card security code." },
    { category: "Do Payment", errorCode: "0001", errorMessage: "Security Code is Invalid Format", description: "" },
    { category: "Do Payment", errorCode: "0004", errorMessage: "Authorization Fail: Invalid Access Token!", description: "" },
    { category: "Do Payment", errorCode: "0006", errorMessage: "Invalid Phone Number", description: "Invalid registration phone number validated by bank API." },
    { category: "Do Payment", errorCode: "0009", errorMessage: "Invalid amount", description: "Wrong format request or exceeded amount." },
    { category: "Do Payment", errorCode: "0010", errorMessage: "Invalid Card Information", description: "" },
    { category: "Do Payment", errorCode: "0022", errorMessage: "Amount less than min transaction amount", description: "" },
    { category: "Do Payment", errorCode: "0023", errorMessage: "Amount bigger than max transaction amount", description: "" },
    { category: "Do Payment", errorCode: "0024", errorMessage: "Insufficient amount", description: "" },
    { category: "Do Payment", errorCode: "0025", errorMessage: "Daily limited amount", description: "" },
    { category: "Do Payment", errorCode: "0026", errorMessage: "Monthly limited amount", description: "" },
    { category: "Do Payment", errorCode: "0028", errorMessage: "Transaction expired", description: "" },
    { category: "Do Payment", errorCode: "0031", errorMessage: "This payment is something wrong. Please try another payment.", description: "Transaction Fail, Bank request failed" },
    { category: "Do Payment", errorCode: "0037", errorMessage: "Payment Transaction is Invalid", description: "" },
    { category: "Do Payment", errorCode: "0038", errorMessage: "Can’t access this payment", description: "MDR status is inactive" },
    { category: "Callback", errorCode: "0000", errorMessage: "Success", description: "Success" },
    { category: "Callback", errorCode: "0007", errorMessage: "Invalid Password", description: "After 5 incorrect OTP entries (for OK dollar)" },
    { category: "Callback", errorCode: "0009", errorMessage: "Invalid amount", description: "" },
    { category: "Callback", errorCode: "0011", errorMessage: "Expired Card", description: "MPU card expired failed" },
    { category: "Callback", errorCode: "0024", errorMessage: "Insufficient amount", description: "" },
    { category: "Callback", errorCode: "0025", errorMessage: "Daily limited amount", description: "" },
    { category: "Callback", errorCode: "0027", errorMessage: "Payment cancelled by user", description: "" },
    { category: "Callback", errorCode: "0028", errorMessage: "Transaction expired", description: "" },
    { category: "Callback", errorCode: "0032", errorMessage: "Bank Transaction Fail", description: "Failed from bank system" },
    { category: "Callback", errorCode: "0039", errorMessage: "Invalid OTP", description: "" },
    { category: "Callback", errorCode: "9999", errorMessage: "[Exception Message]", description: "System Exception" }
];
